{% set name = "ndd" %}
{% set version = "1.10.6" %}
{% set sha256 = "d08d31f297531865f70a130986f0b3d02a9242acbe2c240825f336c0a417a117" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/simomarsili/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('fortran') }}              # [not win]
    - {{ compiler('m2w64_fortran') }}        # [win]
  host:
    - pip
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ndd

about:
  home: https://github.com/simomarsili/ndd
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'ndd is a Python package for Bayesian entropy estimation from discrete data.'

  description: |
    ndd is a Python package for Bayesian entropy estimation from discrete data.
    ndd provides the ndd.entropy function, based on an efficient implementation
    of the Nemenman-Schafee-Bialek (NSB) algorithm. Remarkably, the NSB
    algorithm allows entropy estimation when the number of samples is much
    smaller than the number of classes with non-zero probability.
  doc_url: https://github.com/simomarsili/ndd/blob/master/README.rst
  dev_url: https://github.com/simomarsili/ndd

extra:
  recipe-maintainers:
    - simomarsili
